In [1]:
### Implementation of ICA
### This shows how ICA separates mixed signals

import numpy as np
from sklearn.decomposition import FastICA

# Step 1: Create 2 simple independent signals
S = np.array([[1, 1],
              [2, 1],
              [3, 1],
              [4, 1]])

# Step 2: Mix them
A = np.array([[1, 2],
              [3, 4]])

X = S @ A.T   # Observed mixed data

# Step 3: Apply ICA
ica = FastICA(n_components=2, random_state=0)
U = ica.fit_transform(X)

print("Original Sources:\n", S)
print("Recovered Sources (approx):\n", U)

Original Sources:
 [[1 1]
 [2 1]
 [3 1]
 [4 1]]
Recovered Sources (approx):
 [[-1.26491106  1.37198868]
 [-0.63245553  0.34299717]
 [ 0.63245553 -0.34299717]
 [ 1.26491106 -1.37198868]]


/opt/anaconda3/lib/python3.9/site-packages/sklearn/decomposition/_fastica.py:128: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(


In [7]:
import numpy as np
from sklearn.neural_network import MLPRegressor

X = np.array([[1, 2, 3, 4],
              [2, 3, 4, 5],
              [3, 4, 5, 6],
              [4, 5, 6, 7]], dtype=float)

# Step 2: Create Autoencoder (4 -> 2 -> 4)
autoencoder = MLPRegressor(hidden_layer_sizes=(2,),
                           activation="relu",
                           max_iter=5000,
                           random_state=0)

# Step 3: Train to reproduce input
autoencoder.fit(X, X)

# Step 4: Reconstruct
X_reconstructed = autoencoder.predict(X)

# Step 5: Print 2D hidden representation (the "4 -> 2" part)
W = autoencoder.coefs_[0]      # (4 x 2) input->hidden weights
b = autoencoder.intercepts_[0] # (2,) hidden biases
hidden_2d = np.maximum(0, X @ W + b)  # ReLU: max(0, ...)

print("Original (4 features):\n", X)
print("\nHidden (2 features):\n", np.round(hidden_2d, 2))
print("\nReconstructed:\n", np.round(X_reconstructed, 2))
print("\nWeights:\n",W)
print("\nBias:\n",b)

Original (4 features):
 [[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [4. 5. 6. 7.]]

Hidden (2 features):
 [[4.35 1.56]
 [5.81 2.11]
 [7.27 2.66]
 [8.74 3.21]]

Reconstructed:
 [[2.05 2.76 3.4  3.99]
 [2.52 3.33 4.09 5.  ]
 [2.99 3.89 4.78 6.  ]
 [3.45 4.45 5.47 7.  ]]

Weights:
 [[ 0.47366339  0.16157949]
 [ 0.56718458 -0.17214493]
 [ 0.20035744  0.03395169]
 [ 0.22249123  0.52840198]]

Bias:
 [ 1.24613606 -0.47508091]
