In [1]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score
X, y = make_classification(n_samples=600, n_features=5, random_state=0)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=30, 
    bootstrap=True,
    random_state=0
)

bag.fit(X_train, y_train)

print("Bagging accuracy:", accuracy_score(y_test, bag.predict(X_test)))

Bagging accuracy: 0.9166666666666666


In [2]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

ada = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=2),  # weak learner (stump)
    n_estimators=40,
    learning_rate=1.0,
    random_state=0
)

ada.fit(X_train, y_train)

print("AdaBoost accuracy:", accuracy_score(y_test, ada.predict(X_test)))

AdaBoost accuracy: 0.9222222222222223


In [3]:
from sklearn.ensemble import GradientBoostingClassifier

gbm=GradientBoostingClassifier(
    n_estimators=120,
    learning_rate=0.05,
    random_state=0
)
gbm.fit(X_train, y_train)
print("Bagging accuracy:", accuracy_score(y_test, gbm.predict(X_test)))

Bagging accuracy: 0.9388888888888889


In [86]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import ElasticNet
from sklearn.metrics import mean_squared_error

X, y = make_regression(n_samples=200, n_features=5, noise=10, random_state=0)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0
)

model = ElasticNet(alpha=1.0, l1_ratio=0.5)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("MSE:", mean_squared_error(y_test, y_pred))

MSE: 3027.562035885066


In [87]:
import numpy as np
from sklearn.decomposition import FastICA

S = np.array([[2, 1],
              [3, -2],
              [4, 1],
              [5, -2]])

A = np.array([[2, 1],
              [1, 3]])

X = S @ A.T 

ica = FastICA(n_components=2, random_state=0)
U = ica.fit_transform(X)

print("Original Sources:\n", S)
print("Recovered Sources (approx):\n", U)

Original Sources:
 [[ 2  1]
 [ 3 -2]
 [ 4  1]
 [ 5 -2]]
Recovered Sources (approx):
 [[ 0.99999982 -1.00000018]
 [-1.00000018 -0.99999982]
 [ 1.00000018  0.99999982]
 [-0.99999982  1.00000018]]


In [88]:
import numpy as np
from sklearn.neural_network import MLPRegressor

X = np.array([[2, 3, 4, 5, 6],
              [3, 4, 5, 6, 7],
              [4, 5, 6, 7, 8],
              [5, 6, 7, 8, 9]], dtype=float)


autoencoder = MLPRegressor(hidden_layer_sizes=(3),
                           activation="relu",
                           max_iter=5000,
                           random_state=0)

autoencoder.fit(X, X)

X_reconstructed = autoencoder.predict(X)

W = autoencoder.coefs_[0]      
b = autoencoder.intercepts_[0] 
hidden_2d = np.maximum(0, X @ W + b) 

print("Original (4 features):\n", X)
print("\nHidden (2 features):", np.round(hidden_2d, 2))
print("\nReconstructed:\n", np.round(X_reconstructed, 2))
print("weights\n",W)
print("baises\n",b)

Original (4 features):
 [[2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]
 [5. 6. 7. 8. 9.]]

Hidden (2 features): [[ 0.    4.46  9.34]
 [ 0.    5.5  11.94]
 [ 0.    6.54 14.53]
 [ 0.    7.58 17.12]]

Reconstructed:
 [[2.61 2.85 4.18 4.63 5.55]
 [3.26 3.82 5.08 5.9  6.81]
 [3.91 4.79 5.97 7.17 8.07]
 [4.56 5.76 6.87 8.45 9.33]]
weights
 [[-1.01149722e-20  1.49667020e-01  5.83714746e-01]
 [-8.43654450e-21 -3.56165262e-01  6.61689665e-01]
 [-1.08408667e-18  4.54067603e-01  1.21418891e+00]
 [-3.08411355e-07  2.80378813e-01  4.62621740e-01]
 [-2.78199300e-17  5.11954497e-01 -3.29326390e-01]]
baises
 [-0.71511303 -1.05819437  0.99697324]


In [89]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression


X, y = make_classification(n_samples=150,
                           n_features=3,
                           n_redundant=0,
                           n_informative=2,
                           random_state=0)


labeled = np.arange(15)
unlabeled = np.arange(15, 150)

model = LogisticRegression(solver='liblinear')

for i in range(10):   
    model.fit(X[labeled], y[labeled])

    probs = model.predict_proba(X[unlabeled])[:, 1]

    query = np.argmin(np.abs(probs - 0.5))

    labeled = np.append(labeled, unlabeled[query])
    unlabeled = np.delete(unlabeled, query)

    print("Iteration:", i+1, "| Labeled size:", len(labeled)) 

Iteration: 1 | Labeled size: 16
Iteration: 2 | Labeled size: 17
Iteration: 3 | Labeled size: 18
Iteration: 4 | Labeled size: 19
Iteration: 5 | Labeled size: 20
Iteration: 6 | Labeled size: 21
Iteration: 7 | Labeled size: 22
Iteration: 8 | Labeled size: 23
Iteration: 9 | Labeled size: 24
Iteration: 10 | Labeled size: 25
